name: "Custom Project Status"
description: "Sets project and status for issues and pull requests"
author: "Joao Eduardo Luis <joao@abysmo.io>"

# Add your action's branding here. This will appear on the GitHub Marketplace.
branding:
  icon: "activity"
  color: "purple"

# Define your inputs here.
inputs:
  project-url:
    description: "Project V2 URL"
    required: true

  gh-token:
    description: "GitHub Personal Access Token with write access to 'project'"
    required: true

  default-issue-status:
    description: "Default Status when issue is added to project"
    required: false

  default-pr-status:
    description: "Default Status when pull request is added to project"
    required: false

# Define your outputs here.
outputs:
  project-item-id:
    description: "The Project V2 Item ID that was added to the project"

runs:
  using: node20
  main: dist/index.js
