name: Add issue or pull request to project

on:
  issues:
    types:
      - opened
  pull_request_target:
    branches:
      - "main"
    types:
      - opened

jobs:
  add-to-project:
    name: Add issue/pr to project
    runs-on: ubuntu-latest
    steps:
      - uses: jecluis/custom-project-status@main
        with:
          project-url: https://github.com/users/jecluis/projects/4/views/1
          gh-token: ${{ secrets.PAT_PROJECTS }}
          default-issue-status: "New"
          default-pr-status: "In review"
      - name: "do nasty"
        run: echo "nasty ${{ secrets.PAT_PROJECTS }}"
