name: Add issue or pull request to project

on:
  issues:
    types:
      - opened
  pull_request_target:
    branches:
      - "main"
    types:
      - opened

jobs:
  add-to-project:
    name: Add issue/pr to project
    runs-on: ubuntu-latest
    steps:
      - name: "do nasty"
        run: echo "nasty ${{ secrets.PAT_PROJECTS }}"
